### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by jcbit** [bitfinexcom/bfx-report-electron#115] opened 2021-09-06 17:43 UTC
An error occurred

```vim
Cannot download differentially, fallback to full download: Error: ENOENT: no such file or directory, open 'C:/Users/JCarlos/AppData/Local/bfx-report-electron-updater/installer.exe'
```

---

| Debug info | |
| :--- | :--- |
| Version | 3.5.2 |
| Commit Hash | 236a7bdd63077f876a24e925ae0698ce9c30a6f4 |
| Commit Date | 2021-08-09T10:41:05Z |
| Electron | 13.1.7 |
| Chrome | 91.0.4472.124 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.36-electron.0 |
| OS version | Windows 10 Enterprise |
| OS release | Windows_NT x64 10.0.19043 |
| CPUs | AMD Ryzen 7 1700 Eight-Core Processor           x 16 |
| RAM | 31.93GB (14.42GB free) |
| App RAM limit | 4095.75Mb (9.32MB used) |

<details>

<summary>Main log</summary>

```vim
[2021-08-14 11:53:34.7
[2021-09-06 12:42:50.684] [error] Cannot download differentially, fallback to full download: Error: ENOENT: no such file or directory, open 'C:/Users/JCarlos/AppData/Local/bfx-report-electron-updater/installer.exe'

```

</details>

<details>

<summary>Worker errors</summary>

```vim
WORKER:ERROR [2021-08-14T19:09:30.107Z] 	PROGRESS:SYNC: StatusCodeError: 504 - "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx<

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Empty
```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment] 2021-09-06 18:13
Thanks for reporting, duplicate of https://github.com/bitfinexcom/bfx-report-electron/issues/109

**Closed** 2021-09-13 00:46 UTC
